# Generated by Django 2.2 on 2021-05-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
