# Generated by Django 2.2 on 2021-05-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0002_auto_20210501_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profilepic',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
